### ISSUE TITLE
How to add DirectXTK to UWP app for hololens?

### ISSUE THREAD

**Issue by karann-msft** [microsoft/DirectXTK#115]
From StackOverflow - https://stackoverflow.com/questions/47082356/how-to-add-directxtk-to-uwp-app-for-hololens

I am trying to follow the steps outlined here but I am unable to add a reference at the step when adding DirectXTK as a reference. 
When I skipped this step and proceeded to use DirectXTK in my project it would not compile. 
Any suggestions for getting DirectXTK setup on a UWP project for Hololens? If not this way a different way?

**Comment by walbourn** [comment]
Which ``vcxproj`` did you add to your project? UWP apps should be using ``DirectXTK_Windows10.vcxproj`` which requires VS 2017 / Windows 10 SDK (16299) currently. You might need to contact dngoins as he is the one doing the fork for HoloLens.

**Comment by southie** [comment]
Not to discourage, but DirectXTK was not written in a way to easily support instanced rendering to multiple displays and VPRT (at least at the time when I last forked, I'm still reviewing our current diff). It is possible to do, but does take a fair amount of effort to modify the effects and handle instanced stereo rendering.  Adding support for VPRT also requires a lot of work modifying existing shaders, and adding geometry passthrough shaders for when VPRT is not available. I would be open to creating a pull request if there is support (both community and my employer). It would likely take a lot of input and work from @walbourn to make sure the architecture changes made sense, as well as to finish out the implementation for the effects that we are not using.

**Comment by adamrankin** [comment]
Sorry to dredge up a zombie, but I thought I'd put this out there.

I've duplicated the core features to use DirectXTK with instanced HoloLens rendering. It's not a complete recreation (only a limited subset of shaders have been done).

See here:
https://github.com/adamrankin/HoloIntervention/tree/master/HoloIntervention/Content/Rendering/DirectXTK

**Comment by Edwinzero** [comment]
Hello @walbourn,

Are there any plans for Hololens support in UWP?
I am currently implementing an Hololens medical simulation, but I find there is no support for stereo rendering in DirectXTK for the BasicEffect class. 
Could you give some suggestions about modifying directXTK for stereo rendering support?
Thank you very much for concerning this matter.

**Comment by walbourn** [comment]
At the moment I don't have any plans to add Hololens to the mainline, but mostly because I don't have the hardware.

There are a few folks who have modified the library to support HoloLens (dngoins, southie) which is mostly an issue of doing the instancing needed to render to multiple render targets simultaneously. I've not yet integrated official support because it's not entirely clear the best way to do it non-invasively.

See issue [115](https://github.com/Microsoft/DirectXTK/issues/115), [42](https://github.com/Microsoft/DirectXTK/issues/42), and [41](https://github.com/Microsoft/DirectXTK/pull/41)

**Comment by walbourn** [comment]
There are two basic approaches from what I understand:

1. Render the scene once but have every shader set up with a Geometry Shader to create two instances: each with a different view matrix and RT.

2. Render the scene twice, once for each eye.

The second seems like the better option since it doesn't impact the library as extensively.

> I should mention that I *have* added support for GPU instancing in the most recent release of *DirectX Tool Kit*, although I'm still working on the documentation. That said, this is intended for multiple placement of the same object in the scene rather than rendering to MRTs.
