### ISSUE TITLE
StepTimer.h should use m_qpcFrequency rather than TicksPerSecond for TicksToSeconds()

### ISSUE THREAD

**Issue by wblume** [Microsoft/DirectXTK#120]
Following test code:

`DX::StepTimer testTimer;`
`  uint64 startTicks = testTimer.GetTicks();`
`  Sleep(1000);`
`  uint64 elapsedTicks = testTimer.GetTicks() - startTicks;`
`  char elapsedTimeString[200];`
`  sprintf_s(elapsedTimeString, "Ticks = %lld Seconds = %f\n", elapsedTicks, 
                 testTimer.TicksToSeconds(elapsedTicks));`
 ` OutputDebugStringA(elapsedTimeString);`

 produces on HoloLens emulator (running on Windows10 PC):
    Ticks = 10021899 Seconds = 1.002190           _expected_
but on actual HoloLens 
     Ticks = 1027784 Seconds = **0.102778**     _wrong, off by factor of 10_

This is because fixed conversion value of 10000000 is used in TicksToSeconds() call

The HoloLens has a different tick rate than Windows PC, which causes the discrepancy
m_qpcFrequency gets set to 1015592 rather than 10000000

**Comment by wblume** [comment]
Hi,
Yes, the code is the same.
I think the problem has to do with that the function GetTicks() returns ticks in “QPC units”, but the TicksToSeconds() and SecondsToTicks() functions appear to apply to the “canonical tick format”

**Comment by shawnhar** [comment]
I'm confused because there is no GetTicks() function in eg. https://github.com/walbourn/directx-vs-templates/blob/master/d3d11game_uwp/StepTimer.h

This is why Chuck was asking whether the HoloLens VS project template is perhaps using some different customized version of StepTimer?

**Comment by shawnhar** [comment]
That version of StepTimer is different from the one in directx-vs-templates (which is the same as the VS2017 DirectX UWP templates).  I guess there must be a different version of that specifically in the HoloLens template?

I don't think there is any problem in the HoloLens variant of this file, though.  You are just confusing methods that operate in different units.  That GetTicks method is a simple wrapper around QueryPerformanceCounter, and returns ticks in QPC frequency.  Elsewhere, StepTimer uses a stanardized tick frequency based on the TicksPerSecond constant, which is what methods such as TicksToSeconds operate on.

If calling these methods directly rather than just using the StepTimer to compute steps for you, you'll have to be careful about which units you are using, and convert at the appropriate points (like the StepTimer implementation does in various places).

**Comment by wblume** [comment]
Yes, that is what I am doing now (computing seconds by querying the performance frequency rather than using the class methods), now that I realized what was going on.  Documentation could be improved a bit in the directx-vs-template, to state that GetTicks() returns ticks in QPC resolution.
Thanks for investigating.
Walter

**Comment by walbourn** [comment]
Except there isn't a ``GetTicks`` or a ``GetPerformanceFrequency`` method in the stock ``StepTimer``, just the HoloLens variant. The "convenience wrappers" they added are the confusing part since there's really no reason at all for them to be in ``StepTimer``..

**Comment by wblume** [comment]
I agree.
