### ISSUE TITLE
How to use DirectXTK to develop Hololens app?

### ISSUE THREAD

**Issue by IngoChou** [Microsoft/DirectXTK#133]
Hello,

How to use DirectXTK to develop Hololens app?

Thanks.

**Comment by walbourn** [comment]
There are a few folks who have modified the library to support HoloLens (dngoins, southie) which is mostly an issue of doing the instancing needed to render to multiple render targets simultaneously. I've not yet integrated official support because it's not entirely clear the best way to do it non-invasively.

See issue [115](https://github.com/Microsoft/DirectXTK/issues/115), [42](https://github.com/Microsoft/DirectXTK/issues/42), and [41](https://github.com/Microsoft/DirectXTK/pull/41)

**Comment by IngoChou** [comment]
Yes, that's right. The mainly issue is VPRT feature and using GS shader.

How can I use my custom shader (vs, ps, gs ...)?

I think maybe I can make my app run on hololens and mixed reality portal if I can set and make sure the app is using my custom shaders but not the default effect.

Thanks a lot.

**Comment by insightcoder** [comment]
So what would happen if we try to use DirectXTK SpriteFont within a HoloLens App?  Would anything be displayed?

**Comment by southie** [comment]
Using any of DirectXTK without implementing the appropriate geometry shader and VPRT shaders will result in, I believe, only one eye rendering ( left eye?). It may show you something on the emulator (it only renders one view), but it won't work on the HoloLens.  I suppose you could try to render to texture and use custom shaders from that point, though I haven't tried to do that with SpriteFont.
