### ISSUE TITLE
Open Sdkmesh at runtime

### ISSUE THREAD

**Issue by Besnarb** [Microsoft/DirectXTK#147]
Hello,

I'm trying to open a sdkmesh at runtime (located in 3DObjects folder) the manifest has been modified to get access to the folder.

I have a :
```
StorageFolder^ localFolder = Windows::Storage::KnownFolders::Objects3D;
auto getFileTask = create_task(localFolder->GetFileAsync("cup.sdkmesh"));
getFileTask.then([this](StorageFile^ storageFileSample) {
	std::wostringstream  os;
	// No error here
	os << storageFileSample->Path->Data() << std::endl; 
	OutputDebugString(os.str().c_str());
	// here ERROR: CreateFromSDKMESH failed (80070005) loading 'C:\Users\me\3DObjects\cup.sdkmesh'
	m_model = Model::CreateFromSDKMESH(m_d3dDevice.Get(),  storageFileSample->Path->Data(), *m_fxFactory); 
	});
```
Do you have any idea of what I'm doing wrong ?

Thanks =)

**Comment by walbourn** [comment]
it's probably failing to load the referenced textures in the ``sdkmesh`` because it doesn't have access to them.

You need a more sophisticated solution here, and a custom [IEffectFactory](https://github.com/Microsoft/DirectXTK/wiki/EffectFactory) since the ``StorageFile`` doesn't give you access to the texture files.
