### ISSUE TITLE
Multi-channel reverb

### ISSUE THREAD

**Issue by ifree** [Microsoft/DirectXTK#170]
I don't know where is the right place to ask this question, so I put it here, sorry.

According to XAudio2's [document](https://docs.microsoft.com/en-us/windows/desktop/api/xaudio2fx/nf-xaudio2fx-xaudio2createreverb), the reverb support mono/stereo in 5.1 out.

> The input and output channels must be one of the following combinations.
> Mono input and mono output
> Mono input and 5.1 output
> Stereo input and stereo output
> Stereo input and 5.1 output

If I create the reverb with mono input and 5.1 output, will there any difference among the 6 output channels, or they'll just be the same reverb effect? 

Thanks

**Comment by walbourn** [comment]
As you note, this is really a question about XAudio2's implementation rather than a question about _DirectX Tool Kit for Audio_.

Looking at the source for XAudio 2.7 (the last version to support Windows 7), the reverb supports:

* 1 to 1 channel
* 2 to 2 channel
* 1 to 6 channel (5.1 surround)
* 2 to 6 channel (5.1 surround)

It uses the Princeton Digital Reverb 2004 algorithm.

There are a number of parameters for left vs. right channels. In the mono case, the right channel information is unused.

For mono-processing, the standard approach is to replicate it to the 5 channels (no LFE). For stereo-processing, all left channel information goes to the left surround speakers, right to right, and center is a mix.

**Comment by ifree** [comment]
Thank you very much!
