### ISSUE TITLE
GameRenderer issue

### ISSUE THREAD

**Issue by dudedude1234** [Microsoft/DirectXTK#176]
I wwas setting up Gamerenderer using this

GameRenderer.cpp
'm_controller = Controller::Create(IUnknown^::CreateDeviceResources);'

With this too

Controller.cpp
'Controller^ Controller::Create(_In_ IUnknown^ window)
{
    auto p = ref new Controller(window);
    return static_cast<Controller^>(p);
}

Controller::Controller(_In_ IUnknown^ window) :
    m_isControllerConnected(false)
{
    // Even though all current realizations of MoveLookController install the
    // PointerPressed, PointerMoved, PointerReleased and PointerExited event
    // handlers, it was decided to put all event handler registrations together
    // in the constructor.

    // The windows version of the MoveLookController installs additional event handlers
    // for keyboard input and for relative mouse movement.  There are two
    // parts required to enable relative mouse movement, the event handler
    // and disabling the cursor pointer.

}
'

Yet i keep getting errors:
E2016    a handle to a non-C++/CX class is not allowed    
E2016    a handle to a non-C++/CX class is not allowed    
E2016    a handle to a non-C++/CX class is not allowed    

I posted this here because I'm using the deviceresource script i got from here

**Comment by walbourn** [comment]
The ``^`` in the code above indicates you are using the C++/CX extensions, which requires the ``Controller`` type to be a Windows Runtime class.

The bulk of the code in my templates (including all of DirectX Tool Kit and the DeviceResources) is Standard C++, which uses standard pointers, ``std::unique_ptr<>``, and ``std::shared_ptr`` instead of the C++/CX language extension types.

For more, see [Visual C++ Language Reference (C++/CX)](https://docs.microsoft.com/en-us/cpp/cppcx/visual-c-language-reference-c-cx?view=vs-2019), [Pointers (C++)](https://docs.microsoft.com/en-us/cpp/cpp/pointers-cpp?view=vs-2019), and [Smart Pointers (Modern C++)](https://docs.microsoft.com/en-us/cpp/cpp/smart-pointers-modern-cpp?view=vs-2019).
