### ISSUE TITLE
Expose original image format in WICTextureLoader

### ISSUE THREAD

**Issue by SlidyBat** [microsoft/DirectXTK#187]
When loading, for example, a JPEG image it's format will be `GUID_WICPixelFormat24bppRGB`, but that gets converted to `GUID_WICPixelFormat32bppRGBA` by the loader (the extra alpha channel was added).

I'd like to be able to know whether the original image format had an alpha channel or not so I can automatically detect textures that are potentially translucent, but doesn't seem possible to do that at the moment.

**Comment by walbourn** [comment]
WICTextureLoader is by design very simple. For more sophisticated loading needs, the [DirectXTex](https://github.com/Microsoft/DirectXTex) library is a better choice. See [this blog post](https://walbourn.github.io/direct3d-11-textures-and-block-compression/) for more details on why I have two different libraries here.

**Comment by walbourn** [comment]
I explicitly address this scenario for DirectXTex in this [pull request](https://github.com/microsoft/DirectXTex/pull/150)
