### ISSUE TITLE
/Sharp doesn't do anything to the font created by MakeSpriteFont

### ISSUE THREAD

**Issue by qwexsugare** [microsoft/DirectXTK#209]
I've tried /Sharp now on a multitude of different font creation setups. Here is just one example:
MakeSpriteFont.exe "Segoe UI" /FontSize:20 segoe_ui_20.spritefont /TextureFormat:Rgba32 /Sharp

In the debug sprite font, a regular font can be seen, no different from one without /Sharp

I render it using Direct3D 11 in the code, but as it's already wrong in the debug output, that is not relevant.

**Comment by shawnhar** [comment]
Hi,

The MakeSpriteFont tool relies on System.Drawing for its TrueType rasterization.  The /sharp commandline switch translates to setting the Graphics.PixelOffsetMode property, which will have an effect on some fonts at some point sizes but not otherwise.  I believe this depends on how TrueType hinting for the font in question is set up.

**Comment by qwexsugare** [comment]
Alright, well that is unfortunate, I am experiencing that the fonts have characters which are partially transparent around the edges, making them look blurry (i.e. not sharp) in my game.
Thanks for explaining.
