### ISSUE TITLE
Compatibility with DirectX 9

### ISSUE THREAD

**Issue by Nintynuts** [microsoft/DirectXTK#215]
@walbourn 

The DXTK seems like a great resource, and I'd like to use it in a project I am contributing to that supports DirectX 9-11 (and in future 12). The main issue I'm currently trying to solve is unifying similar code so I was hoping I could use the SimpleMath Extensions, but they have a preprocessor error preventing compilation without inclusion of DX11 or 12. With a local copy I have separated out Viewports into its own file, which seems to be the only dependency on DX11/12 allowing me to use the SimpleMath extensions with DX9. Is this something you would consider doing officially? I can move things around so that including SimpleMath provides both halves and the DX9 compatible bit is in a new file for compatibility.

I'd also be interested in hearing your perspective/knowledge on implementing Fonts, Texture loading ( jpg/png/dds) and surface copying in a way that's compatible with DX9. I've seen there's a DirectXTex library that sounds like it should help, but I couldn't find any documentation on equivalent methods to dx3d9.h

I'm aware a last resort is to make a Zombie DirectX SDK, as your blog explains, but I'd like to avoid it if possible.

Thanks.

**Comment by walbourn** [comment]
What's the technical motivation to support DX9? The only really solid reason to continue to use DX9 is to support Windows XP systems. Otherwise DX11 is supported on everything newer. There's basically nor reason at all to use DX10, as DX11 is supported on the same platforms and has more hardware support.

It's difficult to stop using the legacy DirectX SDK for DX9 development, although you do have a few things to look at.

* DirectXMath is reasonably agnostic, and SimpleMath is as well except for the automatic conversion operator which you could easily do without.

* The more recent D3DCompiler supports Shader Model 2.0 & 3.0, but the DLL itself does not work on Windows XP. See https://walbourn.github.io/hlsl-fxc-and-d3dcompile/

* While this DDSTextureLoader that includes DX9 support is pretty old at this point, you can pretty  easily take the current DDSTextureLoader & WICTextureLoader code from DirectX Tool Kit for DX11 and create a version that supports DX9. See https://walbourn.github.io/ddswithoutd3dx-sample-update/

Keep in mind that there's no support for the DX 9 Developer Runtime on anything newer than Windows 7, so it's not a great experience for a beginner in any case.

It really wouldn't be that difficult to make a DirectX Tool Kit for DX 9 with DDSTextureLoader, SpriteFont, SpriteBatch, WICTextureLoader, ScreenGrab, SimpleMath, VertexTypes, GeometricPrimitive, Model, and PrimitiveBatch. I just don't understand the value of doing it at this point. DX12 is 'pro API' and DX11 is the 'beginner API', so there's really not a lot of reason to go back to DX9. It's also quite a lot of work keeping up two versions of the library, instead of three.

So back to the original question: Why support DX9?

**Comment by walbourn** [comment]
W.r.t. to SimpleMath, the interop is purely optional. I removed the hard block in [this commit](https://github.com/microsoft/DirectXTK/commit/c8b574db77eec1cfef417bf97bfbfc9b645b1d11)

**Comment by Nintynuts** [comment]
The project is a wrapper, so the reason for DX9 is all the games that are DX9 only. I don't think there are many DX10 only games so we might be able to skip it. I think we're only intending windows compatibility back to 7, not XP so hopefully that helps?

**Comment by walbourn** [comment]
OK. I'll work on updating the old DX9 era DDSTextureLoader and make a WICTextureLoader for the DirectXTex package "standalone" copies of the loader. That's probably about as far as I can justify DX9 work :)

**Comment by Nintynuts** [comment]
That would be amazing, thanks!

**Comment by walbourn** [comment]
See [this PR](https://github.com/microsoft/DirectXTex/pull/176) for DirectXTex. It adds 'standalone' versions of DDSTextureLoader and WICTextureLoader for DX9.
