### ISSUE TITLE
missing comdecl.h

### ISSUE THREAD

**Issue by giordi91** [Microsoft/DirectXTK#22]
Hello there, I am trying to compile the DirectXTK but I am having problem with an header: 

`#include <C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include\comdecl.h>`
At line 46 of the Audio.h it is trying to include with full path that header. By googling around it looks like now the comdecl.h should be part of the windows sdk. I dont have the (June 2010) folder at all, but my windows sdk is up to date, I am running windows 10 by the way.
I run a search for comdecl.h and the only one showed up was the one inside the unreal engine.

Anyone got an idea on the problem?
I did not find an official download fo the june 2010 directX only one hosted on other websites like cnet etc.
 I don't have much experience with the win sdk or api in general so sorry if it is a dumb question

**Comment by walbourn** [comment]
This is covered in the [wiki](https://github.com/Microsoft/DirectXTK/wiki/Audio).

If you are building an app with Windows 7 or Windows Vista compatibility, then ``_WIN32_WINNT`` is set to 0x0601 or 0x0600. In that case, you must use the legacy DirectX SDK to get a version of XAudio that is compatible with the target operating system. To resolve the error you are getting, you have to add the DirectX SDK include paths to your projects VC++ Directories--be sure to add it _after_ the existing paths and not before. You must make sure you are using the appropriate _DXSDK vcxproj files so that you are using the XAudio 2.7 version of DirectXTK.

Alternatively, you can set your application to build with ``_WIN32_WINNT`` set to 0x0602 (Windows 8.0), 0x0603 (Windows 8.1), or 0x0A00 (Windows 10) which will make use of the XAudio 2.8 or XAudio 2.9 built into the Windows SDK. You need to make sure you are using the appropriate _Win8 or _Win10 vcxproj file so your DirectXTK is built to match.

**Comment by walbourn** [comment]
Note this setup issue is also covered in the [Adding the DirectX Tool Kit for Audio](https://github.com/Microsoft/DirectXTK/wiki/Adding-the-DirectX-Tool-Kit-for-Audio) tutorial lesson.

**Comment by giordi91** [comment]
Thanks a lot, I actually ended up on that page before, but for some reason I was convinced I needed Xaudio2.7. I am gonna try to compile when I get to my computer and let you know.

M.
