### ISSUE TITLE
Question - Transparent Textures No Color

### ISSUE THREAD

**Issue by alekasm** [microsoft/DirectXTK#224]
Currently I'm trying to load a transparent png image as a texture onto a flat surface. I have a VertexPositionColor "m_batch" for both alpha and opaque drawing, "m_spriteBatch" for SpriteBatch drawing, and "m_texbatch" for VertexPositionTexture drawing.

It seems that both m_spriteBatch and m_texbatch draw ID3D11ShaderResourceView. With that said, I created a test function:

```
    sprites = new std::vector<Microsoft::WRL::ComPtr<ID3D11ShaderResourceView>>();

    Microsoft::WRL::ComPtr<ID3D11ShaderResourceView> texture;
    DirectX::CreateWICTextureFromFile(device.Get(), L"assets/sprites/tree.png", nullptr,
      texture.ReleaseAndGetAddressOf());
  
    Microsoft::WRL::ComPtr<ID3D11Resource> resource;
    DirectX::CreateWICTextureFromFile(device.Get(), L"assets/sprites/tree.png",
      resource.GetAddressOf(),
      texture.ReleaseAndGetAddressOf());

    Microsoft::WRL::ComPtr<ID3D11Texture2D> texture2d;
    resource.As(&texture2d);
    CD3D11_TEXTURE2D_DESC desc;
    texture2d->GetDesc(&desc);

    sprites->push_back(texture);
```

**Side Question:**
[This tutorial](https://github.com/microsoft/DirectXTK/wiki/Sprites-and-textures) shows calling CreateWICTextureFromFile twice. Now my code works just fine with the sprite batch, but this seemed a little odd to me. Perhaps I did not clearly understand or I am making an extra call. 

**Main Problem:**

Here is what drawing a texture using VPT (VertexPositionTexture) versus the Sprite directly:
![differences](https://user-images.githubusercontent.com/45739284/87867553-0e298e00-c95c-11ea-839b-f1e001f36e4f.png)

Now here are how both code is being used:

```
  m_d3dContext->OMSetBlendState(m_states->NonPremultiplied(), NULL, 0xFFFFFFFF);
  m_texbatch->Begin();
  m_effect->SetTextureEnabled(true);
  m_effect->SetTexture(AssetLoader::sprites->at(0).Get()); 
  auto sampler = m_states->LinearClamp();
  m_d3dContext->PSSetSamplers(0, 1, &sampler);
  m_effect->Apply(m_d3dContext.Get());

  const SceneTile& t = tiles[0];
  Vector3 a(0.f, t.height, 0.f);
  Vector3 b(1.f, t.height, 0.f);
  Vector3 c(1.f, t.height + HEIGHT_INCREMENT, 0.f);
  Vector3 d(0.f, t.height + HEIGHT_INCREMENT, 0.f);

  DirectX::VertexPositionTexture v1(a, Vector2(0.f, 1.f) );
  DirectX::VertexPositionTexture v2(b, Vector2(1.f, 1.f) );
  DirectX::VertexPositionTexture v3(c, Vector2(1.f, 0.f) );
  DirectX::VertexPositionTexture v4(d, Vector2(0.f, 0.f) );
  m_texbatch->DrawQuad(v1, v2, v3, v4);
  m_texbatch->End();
```

And for the spritebatch:
```
    m_spriteBatch->Begin(DirectX::SpriteSortMode_Deferred, m_states->NonPremultiplied());

    float scale = 1.f / distance;

    m_spriteBatch->Draw(AssetLoader::sprites->at(0).Get(), DirectX::XMFLOAT2(x, y), nullptr, DirectX::Colors::White, 0.f,
      m_origin, scale);

    m_spriteBatch->End();
```

Also in case this is needed, here is code that is called at the very beginning of my Render function. This setup seems to be correct for what I am doing:

```
  m_d3dContext->RSSetState(m_states->CullNone());

  m_effect->SetTextureEnabled(false);
  m_effect->SetWorld(m_world);
  m_effect->SetView(m_view);
  m_effect->Apply(m_d3dContext.Get());
  m_d3dContext->IASetInputLayout(m_inputLayout.Get());

  m_d3dContext->OMSetBlendState(m_states->Opaque(), NULL, 0xFFFFFFFF);
  m_d3dContext->OMSetDepthStencilState(m_states->DepthDefault(), 0);
```

I don't have all my code pushed, and a lot of this buggy test code is just commented out on my master branch found here:
https://github.com/alekasm/SC2KRender

Do you have any idea why these textures are showing as black, however the sprite when rendered using the sprite batch looks correct (with color)?

Thank you for your time.

**Comment by walbourn** [comment]
The tutorial use CreateWICTextureFromFile just returning the srv, then you change it to CreateWICTextureFromFile returning the both the resource & the srv, and then a third time you modify it to use CreateDDSTextureFromFile instead.

A key issue with your usage of m_effect is that you need to configure BasicEffect *before* you create your input layout or you call Apply.

For example,

auto effect = std::make_unique<BasicEffect>(device.Get());

void const* shaderByteCode;
size_t byteCodeLength;

effect->GetVertexShaderBytecode(&shaderByteCode, &byteCodeLength);

device->CreateInputLayout(VertexPositionColor::InputElements,
                          VertexPositionColor::InputElementCount,
                          shaderByteCode, byteCodeLength,
                          m_inputLayout.ReleaseAndGetAddressOf());

The m_inputLayout here *only* contains Position. There are no texture coordinates consumed by this input layout because the default shader doesn't use them.

If, however, you do:

auto effect = std::make_unique<BasicEffect>(device.Get());
effect->SetTextureEnabled(true);

void const* shaderByteCode;
size_t byteCodeLength;

effect->GetVertexShaderBytecode(&shaderByteCode, &byteCodeLength);

device->CreateInputLayout(VertexPositionColor::InputElements,
                          VertexPositionColor::InputElementCount,
                          shaderByteCode, byteCodeLength,
                          m_inputLayout.ReleaseAndGetAddressOf());

Then the resulting m_inputLayout uses both a position and a texture coordinate.

Therefore, your problem is that you created an input layout that only consumes Position from your vertex data, but then you called Apply to set a shader that consumed both Position & Texture Coordinate. The result is that at runtime, all texture coordinates are 0.

-Chuck Walbourn
Senior SDE, GXP Developer Experience
https://walbourn.github.io/


________________________________

**Comment by walbourn** [comment]
I have updated the [Simple rendering](https://github.com/microsoft/DirectXTK/wiki/Simple-rendering) tutorial which covers ``PrimitiveBatch`` to cover more scenarios including texturing and lighting, and made so to add some specific technical notes about what is happening here w.r.t. to input layouts.
