### ISSUE TITLE
DDSTextureLoader problem while using D3DPOOL_DEFAULT

### ISSUE THREAD

**Issue by Vixen-X** [microsoft/DirectXTK#229]
i have little problem when using CreateTextureFromDDS or File

the problem comes from there

            hr = device->CreateTexture(iWidth, iHeight, iMipCount,
                generateMipsIfMissing ? D3DUSAGE_AUTOGENMIPMAP : 0u,
                fmt, D3DPOOL_DEFAULT,
                pTexture.GetAddressOf(), nullptr);
            if (FAILED(hr))
                return hr;

            ComPtr<IDirect3DTexture9> pStagingTexture;
            hr = device->CreateTexture(iWidth, iHeight, iMipCount,
                0u, fmt, D3DPOOL_SYSTEMMEM, pStagingTexture.GetAddressOf(), nullptr);

my problem is when i trying to resize the window a black screen happen and can't reset the device after some trying i have found problem happen when CreateTexture takes D3DPOOL_DEFAULT i have tried to change it with D3DPOOL_MANAGED but that makes HRESULT return 8876086c 
i using DDSTextureLoader9
here how i creating the device

	LPDIRECT3D9 D3D9;
	LPDIRECT3DDEVICE9 pD3DDevice;
	D3D9 = Direct3DCreate9(D3D_SDK_VERSION);
	if (D3D9 == NULL)
		return;
	D3DPRESENT_PARAMETERS pPresentParms;
	ZeroMemory(&pPresentParms, sizeof(pPresentParms));
	pPresentParms.Windowed = TRUE;
	pPresentParms.BackBufferFormat = D3DFMT_UNKNOWN;
	pPresentParms.SwapEffect = D3DSWAPEFFECT_DISCARD;
	if (FAILED(D3D9->CreateDevice(D3DADAPTER_DEFAULT, D3DDEVTYPE_HAL, GetDesktopWindow(), D3DCREATE_SOFTWARE_VERTEXPROCESSING, &pPresentParms, &pD3DDevice)))
		return;

but it look like the problem always happen even if used D3DXCreateTextureFromFileEx or D3DXCreateTextureFromFileInMemoryEx

if they takes D3DPOOL_DEFAULT i getting black screen when try resize even if used 
 HRESULT hr = pD3DDevice->Reset(&pPresentParms);
it return 8876086c but look like if used D3DPOOL_MANAGED with D3DXCreateTextureFromFileEx or D3DXCreateTextureFromFileInMemoryEx all work fine but can't use D3DPOOL_MANAGED in 

 hr = device->CreateTexture(iWidth, iHeight, iMipCount,
                generateMipsIfMissing ? D3DUSAGE_AUTOGENMIPMAP : 0u,
                fmt, D3DPOOL_DEFAULT,
                pTexture.GetAddressOf(), nullptr);

**Comment by walbourn** [comment]
For my testing of the DX9 version of DDSTextureLoader from [DirectXTex](https://github.com/microsoft/DirectXTex/tree/master/DDSTextureLoader), I used ``IDirect3D9Ex`` because (a) I'm not worried about supporting Windows XP, and (b) the Ex version greatly simplifies the "Lost device" scenario. You may want to consider using it as well, although I'd recommend for new projects moving to DirectX 11 instead.

From [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/direct3d9/lost-devices), your primary issue here is that since you used ``D3DPOOL_DEFAULT`` with 'classic' Direct3D 9, you have to explicitly ``Release`` all such resources *before* you can call ``Reset``. The purpose of ``D3DPOOL_MANAGED`` was to try to simplify this "Lost device" scenario back before Windows Vista.

It sounds like the basic ask here is for version of my DX9 DDSTextureLoader function that lets you use ``D3DPOOL_MANAGED``.

**Comment by Vixen-X** [comment]
ok thanks you very much it would be nice if you got some time to make it work with D3DPOOL_MANAGED
