### ISSUE TITLE
UWP: Setting Mouse::SetVisible(false) stops mouse events.

### ISSUE THREAD

**Issue by trojanfoe** [microsoft/DirectXTK#237]
I would like to hide the mouse cursor, but I still want to know where the mouse is.  If I use Mouse::SetVisible(false) then the mouse state does not report movement.  I assume this is a "UWP thing", but is there anything that can be done about it?

**Comment by walbourn** [comment]
UWP behavior here is a little quirky, but generally if you are using mouse with the cursor hidden, you should use relative movement instead of absolute. See [Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/gaming/relative-mouse-movement).

This is implemented by the [Mouse](https://github.com/microsoft/DirectXTK/wiki/Mouse#absolute-vs-relative-mouse-position) class.

The primary purpose of the ``SetVisible`` method is to deal with the fact that on some platforms the cursor is 'invisible' by default, but yes on Win32 desktop you still get information even when the cursor is hidden.
