### ISSUE TITLE
MeasureString at arbitrary resolutions

### ISSUE THREAD

**Issue by Sainan** [microsoft/DirectXTK#243]
Maybe I'm stupid and/or confused, but I've noticed that `MeasureString` returns the same result, regardless of the resolution of the "canvas" (and `MeasureDrawBounds`' return makes no sense at all). So, given that I can't rely on either of the "measure" functions to help me, how would one draw aligned text at any resolution a user might have?

My solution was to just assume the result of MeasureString is for a 1920x1080 canvas and convert from there, but I assume that's just pure coincidence, right?

**Comment by walbourn** [comment]
``SpriteFont`` is a 'raster' font system not a 'vector' font system. The size returned by ``MeasureString`` and ``MeasureDrawBounds`` therefore is simply a function of the font and the input string, not the render target size. Details on the difference in these methods is covered in the [wiki](https://github.com/microsoft/DirectXTK/wiki/SpriteFont#helpers).

You can use some tricks with ``SpriteBatch`` to do 'canvas scaling'. For example, if you use ``SpriteBatch::SetViewport`` to set a size of 1920x1080 instead of the true size of the render target/backbuffer, it will scale the positions for that canvas. The actual pixels of the output string won't change size. You need to have multiple font-sizes to deal with this. For a concrete example, see [ControllerHelp](https://github.com/microsoft/Xbox-ATG-Samples/blob/master/Kits/ATGTK/ControllerHelp.cpp) which supports 4k through this trick.

If you need arbitrary resolution high-quality fonts, then you need to use a 'vector' font solution like Direct2D/DirectWrite. This solution is not supported by all platforms *DirectX Tool Kit* targets, so I generally stick with [SpriteFont](https://github.com/microsoft/DirectXTK/wiki/SpriteFont) for portability.
