### ISSUE TITLE
DirectXMath: XMMatrixPerspectiveFovLH AspectHByW?

### ISSUE THREAD

**Issue by nlguillemot** [Microsoft/DirectXTK#25]
There's no github for DirectXMath, so I guess this is the next best thing.

I think the `AspectHByW` parameter of `XMMatrixPerspectiveFovLH` should be `AspectWByH`.

If you look at the math to compute `m[0][0]` and `m[1][1]` inside `XMMatrixPerspectiveFovLH`, you'll see that it's identical to the math used in [`gluPerspective`](https://www.opengl.org/sdk/docs/man2/xhtml/gluPerspective.xml). However, `gluPerspective`'s `aspect` parameter is `width/height`.

How could `gluPerspective` and `XMMatrixPerspectiveFovLH` use the same math, but have a different meaning? Futhermore, the results in my app look wrong when I pass `height/width`, but look correct when I pass `width/height`.

**Comment by walbourn** [comment]
The first thing to say is that ``gluPerspective`` should be compared with ``XMMatrixPerspectiveFovRH``, not LH because all OpenGL math is generally column-major, right-handed.

You are correct that the aspectRatio should be ``W / H`` as documented on [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.matrix.xmmatrixperspectivefovlh(v=vs.85).aspx). The name ``AspectHByW`` is confusing so it should probably just be changed to ``AspectRatio``

**Comment by walbourn** [comment]
Note that I've been considering a DirectXMath GitHub for some time. I'll see if I can make that happen this year...

**Comment by walbourn** [comment]
There is now a [DirectXMath GitHub](https://github.com/Microsoft/DirectXMath). I've created [this issue](https://github.com/Microsoft/DirectXMath/issues/1) there.

**Comment by nlguillemot** [comment]
Nice! Well done on making it happen.
