### ISSUE TITLE
Game Controller Input tutorial uses ID3D11ShaderResourceView

### ISSUE THREAD

**Issue by pcbeard** [microsoft/DirectXTK#270]
The [game controller input tutorial](https://github.com/Microsoft/DirectXTK/wiki/Game-controller-input) hasn't been updated for DirectX 12; it's still using ID3D11ShaderResourceView, etc.

**Comment by walbourn** [comment]
The input tutorials including [Keyboard & Mouse](https://github.com/microsoft/DirectXTK/wiki/Mouse-and-keyboard-input) assume you are either using DirectX 11 or are an experienced graphics programmer since you are using DirectX12 and can use the information in the [3D Shapes](https://github.com/microsoft/DirectXTK12/wiki/3D-shapes) tutorial to work it out.

They both have the following under the *Adding a simple scene* section: 

> If using DirectX 12, you will also need a BasicEffect, CommonStates, DescriptorHeap, and ResourceUploadBatch to render this scene. See the 3D Shapes tutorial for more details.

**Comment by walbourn** [comment]
I've updated both of these tutorials to include DX11 & DX12 instructions for the graphics bits:

https://github.com/microsoft/DirectXTK/wiki/Game-controller-input

https://github.com/microsoft/DirectXTK/wiki/Mouse-and-keyboard-input
