### ISSUE TITLE
FitPowerOf2

### ISSUE THREAD

**Issue by Jan-Nekvapil** [microsoft/DirectXTK#273]
There are following errors in function FitPowerOf2

`for (x = maxsize; x > 1; x >>= 1) { if (x <= targetx) break; }`

should be

`for (x = maxsize; x > 1; x >>= 1) { if (x <= origx) break; }`

and

`for (y = maxsize; y > 1; y >>= 1) { if (y <= targety) break; }`

should be

`for (y = maxsize; y > 1; y >>= 1) { if (y <= origy) break; }`

**Comment by walbourn** [comment]
Thanks for the report. This never shows up as a bug because of the usage pattern:

```
UINT twidth = width;
UINT theight = height;
if (loadFlags & WIC_LOADER_FIT_POW2)
{
    LoaderHelpers::FitPowerOf2(width, height, twidth, theight, maxsize);
}
```

The ``FitPowerOf2`` function was lifted from [texconv](https://github.com/microsoft/DirectXTex/blob/master/Texconv/texconv.cpp) where the target height & height are not necessarily the original values.

While your change is correct and clearer within the context of the *DirectX Tool Kit*, it's not the same as the same named function in the other codebase. The function only uses origx, origiy to compute the aspect ratio and to determine if it's x or y dominate in size. It might be clearer if I marked it as:

```
inline void FitPowerOf2(UINT origx, UINT origy, _Inout_ UINT& targetx, _Inout_ UINT& targety, size_t maxsize)
```

**Comment by walbourn** [comment]
https://github.com/microsoft/DirectXTK/commit/f3ae32ffcd225f7461556c22a9a768718bcbff6c
https://github.com/microsoft/DirectXTK12/commit/802285659dae8d019c78b4896956f3a226b250c7
https://github.com/microsoft/DirectXTex/commit/98e48bc3a97b631c41bfccb2071ffc5f7f09b6f5
