### ISSUE TITLE
Instancing - NormalMapEffect without normal maps?

### ISSUE THREAD

**Issue by alekasm** [microsoft/DirectXTK#295]
Hi again, I have a little more free time to look at my project again and I'm reminded where I left off at.

I know that you didnt want to add another permutation to BasicEffect, but none of my models have normal maps - they are all untextured. When loading from Model::CreateFromCMO - it will fail the cast to a NormalMapEffect/PBREffect because of this when we go to UpdateEffects to SetInstancingEnabled.

Is there any workaround for this, programatically?

**Comment by walbourn** [comment]
With *DirectX Toolkit for DX11*, ``NormalMapEffect`` provides default textures if none are given. The main issue is getting the loader to create ``NormalMapEffect`` instances instead of ``BasicEffect``.

If you provide a custom EffectFactory implementation of CreateEffect, you can just make sure it always creates a normal map effect.
