### ISSUE TITLE
Unresolved externals in DirectXTK

### ISSUE THREAD

**Issue by AndreAhmed** [Microsoft/DirectXTK#31]
Hi all,
I'm using DirectXTK and I'm getting unresolved externals when I enable no intersincs, by defining the following #define _XM_NO_INTRINSICS_

    unresolved external symbol "public: void __fastcall DirectX::SpriteBatch

**Comment by walbourn** [comment]
I do not provide a vcxproj for DirectXTK that is built with ``_XM_NO_INTRINSICS_``. Since it's an all inline header, it is important that all code in the same EXE/DLL built with the same settings. To use ``_XM_NO_INTRINSICS_``, you'd need to rebuild the DirectXTK library itself to use that setting.

That said, you really shouldn't have any reason to use ``_XM_NO_INTRINSICS_``. If you need easy individual component access and/or automatic alignment handling, just use [SimpleMath](https://github.com/Microsoft/DirectXTK/wiki/SimpleMath) which is part of the DirectX Tool Kit. It provides constructors and implicit conversion operators which allows you to treat an ``XMVECTOR`` as if it were ``XMFLOAT4`` or vice-versa.
