### ISSUE TITLE
Getting started is confusing

### ISSUE THREAD

**Issue by kyberias** [microsoft/DirectXTK#310]
It doesn't really tell how to install the toolkit which should be the FIRST thing on that page.

**Comment by walbourn** [comment]
Integrating the DirectX Tool Kit into a project is tutorial #3 *after* you are introduced to the basic render loop -and- the DeviceResources abstraction which is used for all the tutorial lessons.

Otherwise, you could try just jumping to [Adding to a VS Solution](https://github.com/microsoft/DirectXTK/wiki/DirectXTK#adding-to-a-vs-solution) but that assumes you already have a suitable project file.

**Comment by walbourn** [comment]
I just added this to the top of *Getting Started*

> This *Getting Started Guide* is a series of tutorial lessons for introducing the various functional parts of the tool kit. If you are just looking for basic integration instructions, see [Adding to a VS solution](https://github.com/microsoft/DirectXTK/wiki/DirectXTK#adding-to-a-vs-solution).
