### ISSUE TITLE
Error on the mouse input

### ISSUE THREAD

**Issue by dudedude1234** [microsoft/DirectXTK#352]
Im having a problem with this method

```
bool StartScreen::isTextClicked()
{
    auto state = m_mouse->Get().GetState();

    RECT rect =
    {
        state.x, state.y, static_cast<long>(m_fontPos.x), static_cast<long>(m_fontPos.y)
    };


    if (rect(state.positionMode()))
        return true;


    //Otherwise, don't do anything
    return false;

}
```

The "rect" and "state" method  on this

```
    if (rect(state.positionMode()))
        return true;
```

keeps putting out this

	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type

**Comment by walbourn** [comment]
The output of the Error Window can be confusing, so I recommend looking at the actual compiler output in the Build window instead for details.

That said, this does not look like valid C++ code:

```
    if (rect(state.positionMode()))
        return true;
```

rect is a ``RECT`` struct and doesn't have an ``operator()``.

The error is probably because this syntax ``state.positionMode()`` is trying to treat the simple value of ``state.positionMode`` as a function pointer. It isn't a method, so you'd just use ``state.positionMode``.

> As with previous questions, you'd be well served to spend some time reading over a basic C/C++ programming tutorial.
