### ISSUE TITLE
CaptureTexture can leak a texture

### ISSUE THREAD

**Issue by LMLB** [Microsoft/DirectXTK#59]
[ScreenGrab.cpp#L107](https://github.com/Microsoft/DirectXTK/blob/master/Src/ScreenGrab.cpp#L107): `hr = d3dDevice->CreateTexture2D(&desc, 0, pStaging.GetAddressOf());`
[ScreenGrab.cpp#L128](https://github.com/Microsoft/DirectXTK/blob/master/Src/ScreenGrab.cpp#L128): `hr = d3dDevice->CreateTexture2D(&desc, 0, pStaging.GetAddressOf());`

If the caller passes a texture in `pStaging`, it leaks if execution hits either of the two lines above.

**Comment by shawnhar** [comment]
I don't see any potential for a leak here.  CaptureTexture is private to this file, and has only two callsites neither of which can ever pass in an initialized texture.

**Comment by LMLB** [comment]
Oh, sorry.

**Comment by walbourn** [comment]
No problem. While you can't get a leak the way it is written, someone could cut & paste the code and end up with one. I try to only use ``GetAddress`` right after declaring a local variable that I know is not initialized, and since it's a parameter I should use ``ReleaseAndGetAddress`` there instead. Note that I avoid using the ``operator&`` overload because the meaning of that operator is different for ``Microsoft::WRL::ComPtr`` and the older ATL ``CComPtr`` so I think it's better practice (see [ComPtr](https://github.com/Microsoft/DirectXTK/wiki/ComPtr)).

This question was also a good reminder that I should have some explicit test coverage for the 'pass in a staging resource` and 'pass in an MSAA resource' code paths instead of just the `pass in a default resource` coverage I already have.
