### ISSUE TITLE
SpriteFont drawing is unexpectedly CPU intensive in Debug builds

### ISSUE THREAD

**Issue by rcurtis** [Microsoft/DirectXTK#65]
While upgrading an old Dx9 project to Dx11 with DirectXT I noticed everything was going smoothly for performance until I started drawing fonts.  CPU usage went up by a factor of 4 and made in impossible to maintain 30 FPS.  

The profiler says the main culprit is DirectX::SpriteFont::Impl::FindGlyph function call.  Is this expected behavior or a bug?  I'm not doing anything too crazy, drawing perhaps 10-15 different pieces of text on the screen.

**Comment by walbourn** [comment]
Are you profiling an optimized Release build or a debug build?

**Comment by rcurtis** [comment]
It is a Debug build.

**Comment by shawnhar** [comment]
Please profile against an optimized build.  It is normal and expected that STL usage in debug builds is much slower due to all the range checks and consistency validation included by the CRT.

**Comment by rcurtis** [comment]
Thanks for the quick replies guys.  With full optimizations turned on, font drawing is no longer a problem.  However, while using a debug build (which is most of development), performance is REALLY bad.  Would it be possible to have a version of SpriteFont that caches the glyph look ups?  I suppose I could render to texture as a work around, but this seems like a reasonable feature request.

**Comment by walbourn** [comment]
"Optimizing" debug performance is quite difficult, especially when leveraging the STL. I'll make a note here to look into it as I've gotten some comments from others on this one. The performance seems to be mainly in the use of the C++ lambda which in non-optimized code is a function call instead of getting inlined. Fixing this would likely require major rewriting of the existing code.

Another option would be for you to change the project settings in your copy of the DirectX TK vcxproj to use optimizations for the ``SpriteFont.cpp`` module in the Debug configuration.

**Comment by shawnhar** [comment]
Or just use the Release configuration of DirectXTK?

Unless you are debugging inside DirectXTK itself, it is reasonable to build your own code for debug but other libraries that you depend on with full optimizations.

**Comment by rcurtis** [comment]
@shawnhar That's a great point guys, I hadn't considered just using the optimized version of DXTK.

**Comment by rcurtis** [comment]
Sorry to necro-post, but I just got back to this project and have a question about using a optimized build in a debug project.  Could I get some pointers on how to accomplish this?  I've tried just linking against a optimized .lib of DXTK but get a boat load of CRT mismatch errors.  How can I actually use an optimized version of DXTK in an otherwise debug build?
