### ISSUE TITLE
Fail to load DDS on some systems.

### ISSUE THREAD

**Issue by rcurtis** [Microsoft/DirectXTK#68]
Greetings,

I am having some weird behavior loading DDS files across a bunch of different hardware/software configurations.  Loading PNGs is never an issue on any of them, but the DDS files tend to load a lot faster for me.  Minimum OS I'm running on is Win7 with SP1 (I beleive SP1 supplies full WIC capabilities).  

I recently tried loading the same dds files using DirectXTex and it works without fail.  I have attached a zip with a project that reliably crashes for me (x86 debug/release should build).  In Game::CreateDevice() near the bottom, the call that fails is CreateWICTextureFromFile, but the next call TestLoadTexture() loads the same DDS file and it succeeds.

I supplied the DDS file and original PNG.  It was created with "texconv.exe -m 1 -f BC3_UNORM".  When the crash happens it comes from CreateWICTextureFromFile returning (0x88982f50) WINCODEC_ERR_COMPONENTNOTFOUND.

[Crash.zip](https://github.com/Microsoft/DirectXTK/files/650221/Crash.zip)

**Comment by walbourn** [comment]
On Windows 8.1 and Windows 10, there is a built-in ``DDS`` codec that can load 2D images without mipmaps for BC1, BC2, and BC3. It cannot load any other ``DDS`` files, and it's not supported on Windows Vista SP2, Windows 7, or Windows 8.0 which is why you are getting ``WINCODEC_ERR_COMPONENTNOTFOUND``.

The [DDSTextureLoader](https://github.com/Microsoft/DirectXTK/wiki/DDSTextureLoader) is an implementation of a ``DDS`` loader that supports 1D, 2D, 3D, mipmaps, and all formats that have DXGI format equivalents which is what you should use instead of [WICTextureLoader](https://github.com/Microsoft/DirectXTK/wiki/WICTextureLoader) for ``DDS`` files.
