### ISSUE TITLE
SpriteBatch error on Xbox One

### ISSUE THREAD

**Issue by steven-ray** [Microsoft/DirectXTK#72]
On an Xbox One build, SpriteBatch::End() results in an exception: "GraphicsMemory singleton not created".

This appears to come from SpriteBatch::Impl::PrepareForRendering() where the following statements are present:
```c++
#if defined(_XBOX_ONE) && defined(_TITLE)
    void* grfxMemory;
    mContextResources->constantBuffer.SetData(deviceContext, transformMatrix, &grfxMemory);
```
In this case, SetData calls GraphicsMemory::Get().Allocate() which fails with the above exception.

My code used to work back in 11/15 with older versions of the DirectXTK.  Revisiting and updating and encountering this error...

**Comment by walbourn** [comment]
This is *by design*. The [January 2016](https://github.com/Microsoft/DirectXTK/releases/tag/jan2016) version of DirectXTK added this requirement so that the library coudl support Xbox One XDK-based using DirectX 11.X "Fast Semantics".

Add the [GraphicsMemory](https://github.com/Microsoft/DirectXTK/wiki/GraphicsMemory) singleton to your application. It's not an automatically created singleton because you must also be sure to call ``Commit`` as part of your presentation loop for proper function.
