### ISSUE TITLE
3D text rendering with spriteFont/spriteBatch

### ISSUE THREAD

**Issue by Rikora** [microsoft/DirectXTK#78]
Hey!

I assume you have seen this question before as I have seen your name relatated to some topics dealing with the same issue, even though the issue remains as the code samples doesn't work for me. But frankly I believe that the solution is not very far away (I hope).

Here is the code so far and the text vanished as I added the matrices transformation to the spriteBatch:

```
Vector3 textPosition = Vector3(0, 3, 6);
		
Matrix m_world = DirectX::XMMatrixScaling(1, -1, 1) * XMMatrixTranslationFromVector(textPosition);
Matrix m_view = m_camera.GetViewMatrix();
Matrix m_proj = m_camera.GetProjectionMatrix();
Matrix WVP = m_world * m_view * m_proj;

m_effects->SetTextureEnabled(true);
m_effects->SetVertexColorEnabled(true);
m_effects->Apply(context);
		
m_spriteBatch->Begin(DirectX::SpriteSortMode_Deferred, nullptr, nullptr, m_states->DepthRead(), 
                                    m_states->CullNone(), nullptr, WVP);
m_font->DrawString(m_spriteBatch.get(), L"Hello", Vector2::Zero, DirectX::Colors::White);
m_spriteBatch->End();
```

Do you spot any errors in the snippet, as I can't understand why this wouldn't work?

[Source](https://blogs.msdn.microsoft.com/shawnhar/2011/01/12/spritebatch-billboards-in-a-3d-world/) 

Thanks for your time.

**Comment by walbourn** [comment]
tThere is still a ``SpriteBatch`` final projection to pixel locations you should disable. As I note on the [wiki](https://github.com/Microsoft/DirectXTK/wiki/SpriteBatch#custom-transform) you can do this via:

    m_spriteBatch->SetRotation(DXGI_MODE_ROTATION_UNSPECIFIED);

The problem with 3D text is that the ``SpriteFont`` class operates in pixel locations rather than normalized coordinates. I have an [issue](https://github.com/Microsoft/DirectXTK/issues/16) open to look at this, but haven't come up with a resolution as of yet. I'm guessing you could just add an inverse offset & scale transformation to the matrix to undo it.

**Comment by Jakobzzz** [comment]
That's unfortunate. How come everything worked fine for Shawn Hargreaves back in 2011 at the source I linked? Did the SpriteFont and SpriteBatch go through a major rework or something?
